version: "2"

services:
  zeebe:
    restart: always
    container_name: zeebe-broker
    image: dokken.azurecr.io/zeebe-nomount:0.24.1
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
