name: Docker Image CI

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: echo ::set-output name=tag_name::$(awk -F ":" 'NR==1{print $2}' Dockerfile)
      id: tag_name_step
    - uses: anothrNick/github-tag-action@master
      with:
        tagging: true
        name:  thuen/zeebe-dev-container
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN2 }} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN2 }}
        REPO_OWNER: AThuen
        CUSTOM_TAG: ${{ steps.tag_name_step.tag_name }} 
        GITHUB_TAG: latest 
    #  docker build . --file Dockerfile --tag apache-php-web:$(awk -F ":" 'NR==1{print $2}' Dockerfile)
